# SPDX-FileCopyrightText: 2026 Amin Zoroufi <aminn.zoroufi@gmail.com>
# SPDX-License-Identifier: LicenseRef-Portfolio-Source-Available
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      javascript-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "05:45"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
