# SPDX-FileCopyrightText: 2026 Amin Zoroufi <aminn.zoroufi@gmail.com>
# SPDX-License-Identifier: LicenseRef-Portfolio-Source-Available
"""Check public-repository links, identity, source notices, and residue."""

from __future__ import annotations

import csv
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).parents[1]
IGNORED_PARTS = {
    ".git",
    ".mypy_cache",
    ".next",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "build",
    "node_modules",
    "tmp",
}
TEXT_SUFFIXES = {
    ".c",
    ".cff",
    ".cmake",
    ".conf",
    ".csv",
    ".h",
    ".html",
    ".json",
    ".md",
    ".mjs",
    ".py",
    ".sch",
    ".sh",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".yaml",
    ".yml",
}
SOURCE_SUFFIXES = {".c", ".h", ".mjs", ".py", ".sh", ".ts", ".tsx"}
SPDX_COPYRIGHT = "SPDX-FileCopyrightText: 2026 Amin Zoroufi <aminn.zoroufi@gmail.com>"
MARKDOWN_LINK = re.compile(r"(?<!!)\[[^]]*]\((?P<target>[^)]+)\)")
ACTION_USE = re.compile(r"^\s*-?\s*uses:\s*[^@\s]+@(?P<revision>[^\s#]+)", re.MULTILINE)

FORBIDDEN: dict[str, re.Pattern[str]] = {
    "unresolved identity placeholder": re.compile(
        r"\[(?:REQUIRED[^]]*|AUTHOR[^]]*|GITHUB_"
        r"USERNAME[^]]*)]"
        r"|AUTHOR_"
        r"FULL_LEGAL_NAME|AUTHOR_"
        r"PUBLIC_EMAIL"
    ),
    "machine-specific absolute path": re.compile(
        r"/" r"Users/|/home/" r"runner/work/|[A-Za-z]:\\" r"Users\\"
    ),
    "private-key material": re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    "GitHub credential": re.compile(r"(?:ghp_|github_pat_)[A-Za-z0-9_]{16,}"),
    "unfinished implementation marker": re.compile(r"\b(?:TO" r"DO|FIX" r"ME|T" r"BD)\b"),
    "prompt or assistant residue": re.compile(
        r"master build "
        r"prompt|chain[- ]of[- ]thought|generated by (?:ChatGPT|Codex)|AI "
        r"assistance",
        re.IGNORECASE,
    ),
}

REQUIRED_FILES = (
    "AUTHORS.md",
    "CITATION.cff",
    "CONTRIBUTING.md",
    "LICENSE.md",
    "NOTICE.md",
    "SECURITY.md",
    "THIRD_PARTY_NOTICES.md",
    "compose.yaml",
    "docs/dependency-license-inventory.csv",
    "docs/report/Intelligent_Industrial_IoT_Monitoring_Platform_EN.pdf",
    "docs/report/Intelligent_Industrial_IoT_Monitoring_Platform_FA.pdf",
    "docs/report/checksums.sha256",
    "hardware/model-provenance.csv",
    "web/app/fonts/OFL.txt",
    "web/app/fonts/provenance.csv",
    "web/package-lock.json",
)

IDENTITY_SNIPPETS = {
    "AUTHORS.md": "Amin Zoroufi <aminn.zoroufi@gmail.com>",
    "CITATION.cff": 'email: "aminn.zoroufi@gmail.com"',
    "LICENSE.md": "Copyright (c) 2026 Amin Zoroufi <aminn.zoroufi@gmail.com>",
    "NOTICE.md": "Copyright (c) 2026 Amin Zoroufi <aminn.zoroufi@gmail.com>",
    "README.md": "Amin Zoroufi",
    "pyproject.toml": 'name = "Amin Zoroufi"',
    "web/package.json": '"name": "Amin Zoroufi"',
}


def ignored(path: Path) -> bool:
    relative = path.relative_to(ROOT)
    return any(part in IGNORED_PARTS for part in relative.parts) or (
        len(relative.parts) >= 2 and relative.parts[:2] == ("data", "models")
    )


def text_files() -> list[Path]:
    return sorted(
        path
        for path in ROOT.rglob("*")
        if path.is_file() and not ignored(path) and path.suffix in TEXT_SUFFIXES
    )


def check_required_files(errors: list[str]) -> None:
    for relative in REQUIRED_FILES:
        if not (ROOT / relative).is_file():
            errors.append(f"missing required public artifact: {relative}")


def check_identity(errors: list[str]) -> None:
    for relative, snippet in IDENTITY_SNIPPETS.items():
        path = ROOT / relative
        if not path.is_file() or snippet not in path.read_text(encoding="utf-8"):
            errors.append(f"identity metadata missing from {relative}")


def check_text(files: list[Path], errors: list[str]) -> None:
    for path in files:
        relative = path.relative_to(ROOT)
        content = path.read_text(encoding="utf-8", errors="replace")
        for label, pattern in FORBIDDEN.items():
            if pattern.search(content):
                errors.append(f"{label}: {relative}")
        if (
            path.suffix in SOURCE_SUFFIXES
            and path.name != "next-env.d.ts"
            and SPDX_COPYRIGHT not in "\n".join(content.splitlines()[:6])
        ):
            errors.append(f"missing project SPDX copyright header: {relative}")


def check_markdown_links(files: list[Path], errors: list[str]) -> None:
    for path in (file for file in files if file.suffix == ".md"):
        content = path.read_text(encoding="utf-8")
        for match in MARKDOWN_LINK.finditer(content):
            target = match.group("target").strip().strip("<>")
            target = target.split(maxsplit=1)[0]
            if target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            local_target = target.split("#", 1)[0]
            if not local_target:
                continue
            if local_target.startswith("/"):
                errors.append(f"absolute local Markdown link in {path.relative_to(ROOT)}: {target}")
                continue
            resolved = (path.parent / local_target).resolve()
            try:
                resolved.relative_to(ROOT)
            except ValueError:
                errors.append(
                    f"Markdown link escapes repository in {path.relative_to(ROOT)}: {target}"
                )
                continue
            if not resolved.exists():
                errors.append(f"broken Markdown link in {path.relative_to(ROOT)}: {target}")


def check_action_pins(files: list[Path], errors: list[str]) -> None:
    workflow_files = [
        path
        for path in files
        if path.parent == ROOT / ".github/workflows" and path.suffix == ".yml"
    ]
    if not workflow_files:
        errors.append("no GitHub Actions workflows found")
        return
    for path in workflow_files:
        content = path.read_text(encoding="utf-8")
        for match in ACTION_USE.finditer(content):
            revision = match.group("revision")
            if re.fullmatch(r"[0-9a-f]{40}", revision) is None:
                errors.append(
                    f"GitHub Action is not pinned to a full commit SHA: {path.relative_to(ROOT)}"
                )


def check_font_provenance(errors: list[str]) -> None:
    provenance = ROOT / "web/app/fonts/provenance.csv"
    if not provenance.is_file():
        return
    with provenance.open(encoding="utf-8", newline="") as source:
        rows = list(csv.DictReader(source))
    expected_names = {"geist-latin.woff2", "geist-mono-latin.woff2"}
    if {row.get("file") for row in rows} != expected_names:
        errors.append("dashboard font provenance does not list the exact bundled font set")
        return
    for row in rows:
        filename = row["file"]
        font_path = provenance.parent / filename
        if not font_path.is_file():
            errors.append(f"missing dashboard font binary: {filename}")
            continue
        checksum = hashlib.sha256(font_path.read_bytes()).hexdigest()
        if checksum != row.get("sha256"):
            errors.append(f"dashboard font checksum mismatch: {filename}")
        if row.get("license") != "SIL-OFL-1.1":
            errors.append(f"unexpected dashboard font license: {filename}")


def main() -> None:
    errors: list[str] = []
    files = text_files()
    check_required_files(errors)
    check_identity(errors)
    check_text(files, errors)
    check_markdown_links(files, errors)
    check_action_pins(files, errors)
    check_font_provenance(errors)
    if errors:
        for error in sorted(set(errors)):
            print(f"ERROR: {error}")
        raise SystemExit(1)
    print(f"repository hygiene passed: {len(files)} public text files inspected")


if __name__ == "__main__":
    main()
